### ISSUE TITLE
Coupling to other codes with PreCice.

### ISSUE THREAD

**Issue by stefano2734** [polycfd/apecss#27]
Coupling to other codes with PreCice by TU Munich.

https://precice.org/

perhaps a possibility for a wide use of this software with other FEM and CFD  Codes like Calculix, Openfoam and others.

Acoular is a software to see sources in measurement.
https://www.acoular.org/

perhaps is here a link possible between numerical calculations and measurement.

**Comment by fabiandenner** [comment]
Hi Stefano, 

Thanks for these suggestions. Coupling APECSS to other software codes does not require (but, of course, may use) a coupling library like preCiCE. Simply link APECSS as a library to your favourite CFD code and call the desired APECSS functions directly in the CFD code. More information can be found in the section 2 of the [APECSS documentation](/documentation/).

Please feel free to contact me if you have any specific questions.

Best regards,
Fabian
